apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-admin-role
rules:
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete


